# -*- coding: utf-8 -*-
"""GCN_Models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zxu-jOG2LQKe1R8MztwLWxO4MDUcQlJq
"""

# STEP 1: Install dependencies
!pip install torch torchvision torchaudio
!pip install torch-scatter torch-sparse torch-geometric -f https://data.pyg.org/whl/torch-2.0.0+cpu.html

# STEP 2: Import packages
import pandas as pd
import numpy as np
from sklearn.neighbors import NearestNeighbors
import torch
from torch_geometric.data import Data

# STEP 3: Upload your cleaned CSV file
from google.colab import files
uploaded = files.upload()  # upload 'clean_listings_32827.csv'

# STEP 4: Load and inspect the data
df = pd.read_csv('clean_listings_32827.csv')
print(df.shape)
df.head()

# Assuming your dataset is a pandas DataFrame named df
# Replace with actual name if different

categorical_columns = df.select_dtypes(include=['object', 'category']).columns

print("Categorical columns and their unique values:\n")
for col in categorical_columns:
    print(f"{col}:")
    print(df[col].unique())
    print("-" * 40)

# Step 1: Define the original numerical features
features = ['bedrooms', 'bathrooms', 'squarefootage', 'lotsize', 'yearbuilt']
X_num = df[features].values.astype(np.float32)

# Step 2: One-hot encode 'propertytype'
property_dummies = pd.get_dummies(df['propertytype'], prefix='type')
X_cat = property_dummies.values.astype(np.float32)

# Step 3: Combine numerical and categorical features
X = np.hstack([X_num, X_cat])

# Step 4: Targets and coordinates
y = df['log_price'].values.astype(np.float32)
coords = df[['latitude', 'longitude']].values.astype(np.float64)

print("X shape:", X.shape)
print("First 5 rows of X:\n", X[:5])

print("\ny shape:", y.shape)
print("First 5 values of y:", y[:5])

# STEP 6: Compute k-nearest neighbors using Haversine distance
coords_rad = np.radians(coords)
k = 8

nbrs = NearestNeighbors(n_neighbors=k + 1, algorithm='ball_tree', metric='haversine').fit(coords_rad)
distances, indices = nbrs.kneighbors(coords_rad)

edge_index_list = []
edge_attr_list = []

for i, neighbors in enumerate(indices):
    for j, neighbor in enumerate(neighbors[1:]):  # skip self
        edge_index_list.append([i, neighbor])
        edge_attr_list.append([distances[i][j + 1]])  # in radians

from sklearn.preprocessing import StandardScaler
# Step 1: Extract numeric and one-hot parts
X_numeric = df[['bedrooms', 'bathrooms', 'squarefootage', 'lotsize', 'yearbuilt']].values.astype(np.float32)
X_one_hot = pd.get_dummies(df['propertytype']).values.astype(np.float32)  # or however you created it
property_categories = list(pd.get_dummies(df['propertytype']).columns)

# Step 2: Scale numeric features
scaler = StandardScaler()
X_numeric_scaled = scaler.fit_transform(X_numeric)

# Step 3: Combine
X_combined = np.concatenate([X_numeric_scaled, X_one_hot], axis=1)

# Step 4: Tensor conversion
x = torch.tensor(X_combined, dtype=torch.float32)
y = torch.tensor(df['log_price'].values, dtype=torch.float32)

import joblib
joblib.dump(scaler, "feature_scaler.pkl")

# STEP 8: Create PyTorch Geometric Data object
data = Data(x=x, edge_index=edge_index, edge_attr=edge_attr, y=y)

# Confirm the graph object
print(data)

import matplotlib.pyplot as plt

# Get positions
pos = df[['longitude', 'latitude']].values

# Get edge list
edges = data.edge_index.numpy()

plt.figure(figsize=(10, 10))

# Plot edges
for i in range(edges.shape[1]):
    src, tgt = edges[:, i]
    x_coords = [pos[src][0], pos[tgt][0]]
    y_coords = [pos[src][1], pos[tgt][1]]
    plt.plot(x_coords, y_coords, color='lightgray', linewidth=0.5, alpha=0.5)

# Plot nodes
plt.scatter(pos[:, 0], pos[:, 1], c=df['log_price'], cmap='viridis', s=10)
plt.colorbar(label='Log Price')
plt.title("Graph Visualization by Geographic Location")
plt.xlabel("Longitude")
plt.ylabel("Latitude")
plt.axis('equal')
plt.show()

from torch_geometric.utils import train_test_split_edges

# Split into training / val / test masks
num_nodes = data.num_nodes
perm = torch.randperm(num_nodes)
train_idx = perm[:int(0.8 * num_nodes)]
test_idx  = perm[int(0.8 * num_nodes):]

data.train_mask = torch.zeros(num_nodes, dtype=torch.bool)
data.train_mask[train_idx] = True

data.test_mask = torch.zeros(num_nodes, dtype=torch.bool)
data.test_mask[test_idx] = True

import torch.nn as nn
import torch.nn.functional as F
from torch_geometric.nn import GCNConv

class GCNRegressor(nn.Module):
    def __init__(self, in_channels, hidden_channels):
        super().__init__()
        self.conv1 = GCNConv(in_channels, hidden_channels)
        self.conv2 = GCNConv(hidden_channels, hidden_channels)
        self.lin = nn.Linear(hidden_channels, 1)

    def forward(self, x, edge_index):
        x = F.relu(self.conv1(x, edge_index))
        x = F.relu(self.conv2(x, edge_index))
        return self.lin(x).squeeze()

model = GCNRegressor(in_channels=data.x.shape[1], hidden_channels=32)
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)
loss_fn = nn.MSELoss()

for epoch in range(1000):
    model.train()
    optimizer.zero_grad()
    out = model(data.x, data.edge_index)
    loss = loss_fn(out[data.train_mask], data.y[data.train_mask])
    loss.backward()
    optimizer.step()
    if epoch % 10 == 0:
        test_loss = loss_fn(out[data.test_mask], data.y[data.test_mask])
        print(f'Epoch {epoch}, Train Loss: {loss.item():.4f}, Test Loss: {test_loss.item():.4f}')

# ⚠️ Run this only once per session
# Restart runtime if this fails midway
!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
!pip install torch-scatter torch-sparse torch-geometric -f https://data.pyg.org/whl/torch-2.0.1+cu118.html

import torch
import torch.nn.functional as F
from torch.nn import Linear
from torch_geometric.nn import TransformerConv

class PD_TGCN(torch.nn.Module):
    def __init__(self, in_channels, hidden_channels=64, heads=2, dropout=0.1):
        super(PD_TGCN, self).__init__()
        self.conv1 = TransformerConv(in_channels, hidden_channels, heads=heads, edge_dim=1)
        self.conv2 = TransformerConv(hidden_channels * heads, hidden_channels, heads=heads, edge_dim=1)
        self.lin1 = Linear(hidden_channels * heads, hidden_channels)
        self.lin2 = Linear(hidden_channels, 1)
        self.dropout = dropout

    def forward(self, x, edge_index, edge_attr):
        x = self.conv1(x, edge_index, edge_attr)
        x = F.relu(x)
        x = F.dropout(x, p=self.dropout, training=self.training)

        x = self.conv2(x, edge_index, edge_attr)
        x = F.relu(x)
        x = F.dropout(x, p=self.dropout, training=self.training)

        x = self.lin1(x)
        x = F.relu(x)
        x = F.dropout(x, p=self.dropout, training=self.training)

        return self.lin2(x).squeeze()

transformer_model = PD_TGCN(in_channels=x.shape[1])

transformer_optimizer = torch.optim.Adam(transformer_model.parameters(), lr=0.02, weight_decay=1e-5)

# Train the transformer model
import torch
import torch.nn.functional as F
from sklearn.model_selection import train_test_split

# Split your indices into train and test
indices = np.arange(len(y))
train_idx, test_idx = train_test_split(indices, test_size=0.2, random_state=42)

train_idx = torch.tensor(train_idx, dtype=torch.long)
test_idx = torch.tensor(test_idx, dtype=torch.long)

# Train the transformer GCN
def train_transformer(model, data, epochs=300):
    for epoch in range(epochs):
        model.train()
        transformer_optimizer.zero_grad()
        out = model(data.x, data.edge_index, data.edge_attr)
        loss = F.mse_loss(out[train_idx], data.y[train_idx])
        loss.backward()
        transformer_optimizer.step()

        if epoch % 10 == 0 or epoch == epochs - 1:
            model.eval()
            with torch.no_grad():
                test_out = model(data.x, data.edge_index, data.edge_attr)
                test_loss = F.mse_loss(test_out[test_idx], data.y[test_idx])
                print(f"Epoch {epoch}, Train Loss: {loss.item():.4f}, Test Loss: {test_loss.item():.4f}")

# Normalize edge_attr (standardize)
data.edge_attr = (data.edge_attr - data.edge_attr.mean()) / data.edge_attr.std()

train_transformer(transformer_model, data, epochs=50)

def one_hot_property_type(value, categories):
    """Create a one-hot encoded vector for a single property type string."""
    return np.array([1.0 if value == cat else 0.0 for cat in categories], dtype=np.float32)

def predict_price(new_house, df_existing, trained_model, scaler, property_categories, k=8):
    feature_cols = ['bedrooms', 'bathrooms', 'squarefootage', 'lotsize', 'yearbuilt']
    raw_numeric = np.array([[new_house[feat] for feat in feature_cols]], dtype=np.float32)
    scaled_numeric = scaler.transform(raw_numeric)

    # ✅ Manual one-hot encoding using categories from training
    onehot_property = one_hot_property_type(new_house['propertytype'], property_categories)

    # Combine scaled numeric + one-hot categorical features
    full_features = np.hstack([scaled_numeric, onehot_property.reshape(1, -1)])

    # Coordinates for neighbor lookup
    coords_existing = df_existing[['latitude', 'longitude']].values
    coords_new = np.array([[new_house['latitude'], new_house['longitude']]])
    coords_rad_existing = np.radians(coords_existing)
    coords_rad_new = np.radians(coords_new)

    nbrs = NearestNeighbors(n_neighbors=k, metric='haversine').fit(coords_rad_existing)
    distances_rad, indices = nbrs.kneighbors(coords_rad_new)
    distances_km = distances_rad * 6371

    # Build new input graph
    neighbor_feats = data.x[indices[0]].cpu().numpy()
    all_features = np.vstack([full_features, neighbor_feats])
    x = torch.tensor(all_features, dtype=torch.float32)

    edge_index = torch.tensor([[0]*k, list(range(1, k+1))], dtype=torch.long)
    edge_attr = torch.tensor(distances_km[0][:, None], dtype=torch.float32)
    edge_attr = (edge_attr - edge_attr.mean()) / edge_attr.std()
    edge_index = torch.cat([edge_index, edge_index.flip(0)], dim=1)
    edge_attr = torch.cat([edge_attr, edge_attr], dim=0)

    # Inference
    trained_model.eval()
    with torch.no_grad():
        if isinstance(trained_model, PD_TGCN):
            out = trained_model(x, edge_index, edge_attr)
            print("GCN Model ")
        else:
            out = trained_model(x, edge_index)
            print("Transformer GCN Model ")

        log_price = np.clip(out[0].item(), 10, 15)
        price = round(np.exp(log_price), 2)

    print("Predicted price: $", price)
    return price

sample_inputs = [
    {
        'latitude': 28.540, 'longitude': -81.379,  # Downtown Orlando
        'bedrooms': 3, 'bathrooms': 2, 'squarefootage': 1450,
        'lotsize': 0.15, 'yearbuilt': 1985, 'propertytype': 'single_family'
    },
    {
        'latitude': 28.602, 'longitude': -81.200,  # Oviedo
        'bedrooms': 2, 'bathrooms': 1.5, 'squarefootage': 1100,
        'lotsize': 0.08, 'yearbuilt': 2005, 'propertytype': 'townhouse'
    },
    {
        'latitude': 28.385, 'longitude': -81.562,  # Celebration
        'bedrooms': 1, 'bathrooms': 1, 'squarefootage': 900,
        'lotsize': 0.05, 'yearbuilt': 2010, 'propertytype': 'condo'
    },
    {
        'latitude': 28.451, 'longitude': -81.469,  # Dr. Phillips
        'bedrooms': 5, 'bathrooms': 4, 'squarefootage': 4000,
        'lotsize': 0.4, 'yearbuilt': 2018, 'propertytype': 'single_family'
    },
    {
        'latitude': 28.565, 'longitude': -81.242,  # Winter Park
        'bedrooms': 3, 'bathrooms': 2.5, 'squarefootage': 1800,
        'lotsize': 0.12, 'yearbuilt': 1995, 'propertytype': 'townhouse'
    },
    {
        'latitude': 28.693, 'longitude': -81.556,  # Apopka
        'bedrooms': 0, 'bathrooms': 0, 'squarefootage': 0,
        'lotsize': 1.0, 'yearbuilt': 2023, 'propertytype': 'land'
    },
    {
        'latitude': 28.365, 'longitude': -81.265,  # Kissimmee
        'bedrooms': 4, 'bathrooms': 3, 'squarefootage': 2600,
        'lotsize': 0.13, 'yearbuilt': 2015, 'propertytype': 'single_family'
    },
    {
        'latitude': 28.489, 'longitude': -81.191,  # East Orlando
        'bedrooms': 2, 'bathrooms': 1, 'squarefootage': 950,
        'lotsize': 0.1, 'yearbuilt': 1980, 'propertytype': 'condo'
    },
    {
        'latitude': 28.524, 'longitude': -81.465,  # MetroWest
        'bedrooms': 3, 'bathrooms': 2, 'squarefootage': 1350,
        'lotsize': 0.12, 'yearbuilt': 2003, 'propertytype': 'multi-family'
    },
    {
        'latitude': 28.677, 'longitude': -81.209,  # Sanford
        'bedrooms': 5, 'bathrooms': 3.5, 'squarefootage': 3100,
        'lotsize': 0.25, 'yearbuilt': 2020, 'propertytype': 'single_family'
    }
]
for i, house in enumerate(sample_inputs, 1):
    print(f"\n--- Prediction for Sample {i} ---")
    predict_price(house, df_existing=df, trained_model=transformer_model, scaler=scaler, property_categories=property_categories)
    predict_price(house, df_existing=df, trained_model=model, scaler=scaler, property_categories=property_categories)

import numpy as np
import matplotlib.pyplot as plt

def evaluate_model(model, data, test_idx, label='GCN'):
    model.eval()
    with torch.no_grad():
        if isinstance(model, PD_TGCN):
            pred_log = model(data.x, data.edge_index, data.edge_attr)[test_idx]
        else:
            pred_log = model(data.x, data.edge_index)[test_idx]

        true_log = data.y[test_idx]

        # Convert back from log to dollar values
        y_true = np.exp(true_log.cpu().numpy())
        y_pred = np.exp(pred_log.cpu().numpy())

        # Plot
        plt.figure(figsize=(6, 6))
        plt.scatter(y_true, y_pred, alpha=0.6)
        plt.plot([y_true.min(), y_true.max()], [y_true.min(), y_true.max()], 'r--')
        plt.xlabel("True Price ($)")
        plt.ylabel("Predicted Price ($)")
        plt.title(f"{label} Price Prediction Calibration")
        plt.grid(True)
        plt.show()

        # Return predictions if you want to analyze further
        return y_true, y_pred

y_true_gcn, y_pred_gcn = evaluate_model(model, data, test_idx, label='GCN')
y_true_tgnn, y_pred_tgnn = evaluate_model(transformer_model, data, test_idx, label='Transformer GCN')

sample_input1 = {
    'latitude': 28.366,
    'longitude': -81.268,
    'bedrooms': 4,
    'bathrooms': 3,
    'squarefootage': 2600,
    'lotsize': 0.13,
    'yearbuilt': 2015
}
sample_input2 = {
    'latitude': 28.355,
    'longitude': -81.270,
    'bedrooms': 5,
    'bathrooms': 4,
    'squarefootage': 3400,
    'lotsize': 0.25,
    'yearbuilt': 2020
}
sample_input3 = {
    'latitude': 28.371,
    'longitude': -81.260,
    'bedrooms': 2,
    'bathrooms': 2,
    'squarefootage': 1200,
    'lotsize': 0.05,
    'yearbuilt': 2012
}
sample_input4 = {
    'latitude': 28.362,
    'longitude': -81.250,
    'bedrooms': 3,
    'bathrooms': 2,
    'squarefootage': 1800,
    'lotsize': 0.2,
    'yearbuilt': 1970
}
sample_input5 = {
    'latitude': 28.345,
    'longitude': -81.245,
    'bedrooms': 2,
    'bathrooms': 1,
    'squarefootage': 950,
    'lotsize': 0.1,
    'yearbuilt': 1985
}
for i, sample in enumerate([sample_input1, sample_input2, sample_input3, sample_input4, sample_input5], 1):
    print(f"\nPrediction for Sample {i} (GCN):")
    predict_price(sample, df_existing=df, trained_model=model, scaler=scaler)

    print(f"Prediction for Sample {i} (Transformer GCN):")
    predict_price(sample, df_existing=df, trained_model=transformer_model, scaler=scaler)